apiVersion: v1
kind: Service
metadata:
  name: artist-service-mongo
  labels:
    app: artist-service
spec:
  ports:
    - port: 27017
  selector:
    app: artist-service
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-service-mongo-deployment
  labels:
    app: artist-service
spec:
  selector:
    matchLabels:
      app: artist-service
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: artist-service
        tier: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
              name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-service-server-deployment
  labels:
    app: artist-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artist-service-server
  template:
    metadata:
      labels:
        app: artist-service-server
    spec:
      containers:
        - name: artist-service-server
          image: robindeclerck/artist-service
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8052
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: MONGODB_HOST
              value: "artist-service-mongo"
            - name: MONGODB_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: artist-service-server
  labels:
    app: artist-service-server
spec:
  type: NodePort
  selector:
    app: artist-service-server
  ports: # Forward incoming connections on port 8052 to the target port 8052
    - name: http
      port: 8052
      targetPort: 8052