version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo-db'
    environment:
      - MONGO_INITDB_DATABASE=artist-service
      - MONGO_INITDB_ROOT_USERNAME=artist
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017-27019:27017-27019'